name: wittig-ch121
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - bottleneck=1.3.2
  - brotli=1.0.7
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - decorator=5.1.1
  - deepchem=2.8.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - idna=3.7
  - importlib_resources=6.1.1
  - ipython=8.15.0
  - ipywidgets=8.1.2
  - jedi=0.18.1
  - joblib=1.4.2
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0=21_mkl
  - libcblas=3.9.0=21_mkl
  - libdeflate=1.20
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0=21_mkl
  - libopenblas=0.3.25
  - libpng=1.6.43
  - libsqlite=3.45.2
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.3.1
  - llvm-openmp=18.1.6
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - numexpr=2.7.3
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - packaging=24.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=23.3
  - platformdirs=4.2.2
  - pooch=1.8.1
  - prompt-toolkit=3.0.43
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py3dmol=2.1.0
  - pyaml=20.4.0
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.0.1
  - scipy=1.10.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.45.2
  - stack_data=0.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.11.0
  - tzdata=2023c
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.6.2
      - cloudpickle==3.0.0
      - dgl==2.2.1
      - dgllife==0.3.2
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fsspec==2024.6.0
      - future==1.0.0
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - hyperopt==0.2.7
      - importlib-metadata==7.1.0
      - jinja2==3.1.4
      - keras==3.3.3
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.2.1
      - opt-einsum==3.3.0
      - optree==0.11.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py4j==0.10.9.7
      - pygments==2.18.0
      - rdkit==2023.9.6
      - rich==13.7.1
      - sympy==1.12.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - tqdm==4.66.4
      - typing-extensions==4.12.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.2
